name: Docs render check
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: macos-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Install pandoc
        run: 'brew install pandoc

          '
      - id: measurement-3
        name: Record Measurement After Install pandoc
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install pandoc
          task: get-measurement
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install ASReview with docs dependencies
        run: 'python -m pip install .[docs]

          '
      - id: measurement-6
        name: Record Measurement After Install ASReview with docs dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install ASReview with docs dependencies
          task: get-measurement
      - name: Build HTML
        run: 'python -m sphinx -W --keep-going --color docs/source/ build/html/

          '
      - id: measurement-8
        name: Record Measurement After Build HTML
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Build HTML
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
